const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    darkMode: ['class'],
    content: [
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './app/**/*.{ts,tsx}',
        './src/**/*.{ts,tsx}',
    ],
    prefix: '',
    theme: {
        container: {
            center: 'true',
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            keyframes: {
                'accordion-down': {
                    from: {
                        height: '0',
                    },
                    to: {
                        height: 'var(--radix-accordion-content-height)',
                    },
                },
                'accordion-up': {
                    from: {
                        height: 'var(--radix-accordion-content-height)',
                    },
                    to: {
                        height: '0',
                    },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
            lineHeight: {
                '4.5': '18px',
                '5.5': '22px',
                '11': '44px',
                '12': '48px',
                '14': '56px',
                '16': '64px',
                '18': '72px',
                '20': '80px',
                '24': '96px',
                '28': '112px',
            },
            transitionProperty: {
                width: 'width',
            },
            colors: {
                primary: {
                    '50': '#F5F6FF',
                    '300': '#B9BDEA',
                    '500': '#5162FF',
                    '700': '#3555AC',
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    '300': '#96EAF1',
                    '500': '#15D6E8',
                    '700': '#09A8B7',
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                tertiary: {
                    '300': '#EDCBFF',
                    '500': '#BD47FB',
                    '700': '#8919C4',
                },
                success: {
                    '300': '#AAE8B0',
                    '500': '#5CD167',
                    '700': '#0F921B',
                },
                warning: {
                    '300': '#FFDB93',
                    '500': '#FAAD14',
                    '700': '#C58300',
                    '900': '#BD7003',
                },
                error: {
                    '300': '#FF9FAE',
                    '500': '#FF658A',
                    '700': '#C30C38',
                    '900': '#A50114',
                },
                neutral: {
                    '1': '#141416',
                    '2': '#23262F',
                    '3': '#353945',
                    '4': '#777E91',
                    '5': '#B1B5C4',
                    '6': '#E6E8EC',
                    '7': '#F4F5F6',
                    '8': '#FCFCFD',
                    '50': '#FBFAFC',
                    '100': '#F1F5F9',
                    '200': '#E2E8F0',
                    '300': '#CBD5E1',
                    '400': '#94A3B8',
                    '500': '#64748B',
                    '600': '#475569',
                    '700': '#334155',
                    '800': '#1E293B',
                    '900': '#002133',
                    DEFAULT: '#353945',
                },
                black: {
                    '10': 'rgba(0, 0, 0, 0.1)',
                    '20': 'rgba(0, 0, 0, 0.2)',
                    '30': 'rgba(0, 0, 0, 0.3)',
                    '40': 'rgba(0, 0, 0, 0.4)',
                    '50': 'rgba(0, 0, 0, 0.5)',
                    '60': 'rgba(0, 0, 0, 0.6)',
                    '70': 'rgba(0, 0, 0, 0.7)',
                    '80': 'rgba(0, 0, 0, 0.8)',
                    '90': 'rgba(0, 0, 0, 0.9)',
                    DEFAULT: '#000000',
                },
                white: {
                    '5': 'rgba(255, 255, 255, 0.05)',
                    '10': 'rgba(255, 255, 255, 0.1)',
                    '20': 'rgba(255, 255, 255, 0.2)',
                    '30': 'rgba(255, 255, 255, 0.3)',
                    '40': 'rgba(255, 255, 255, 0.4)',
                    '50': 'rgba(255, 255, 255, 0.5)',
                    '60': 'rgba(255, 255, 255, 0.6)',
                    '70': 'rgba(255, 255, 255, 0.7)',
                    '80': 'rgba(255, 255, 255, 0.8)',
                    '90': 'rgba(255, 255, 255, 0.9)',
                    DEFAULT: '#FFFFFF',
                },
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                chart: {
                    '1': 'hsl(var(--chart-1))',
                    '2': 'hsl(var(--chart-2))',
                    '3': 'hsl(var(--chart-3))',
                    '4': 'hsl(var(--chart-4))',
                    '5': 'hsl(var(--chart-5))',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
        },
        fontFamily: {
            primary: ['GT Super Display', ...defaultTheme.fontFamily.serif],
            secondary: [
                'Suisse International',
                ...defaultTheme.fontFamily.sans,
            ],
            tertiary: ['Roboto Mono', ...defaultTheme.fontFamily.sans],
            numerical: ['IBM Plex Sans', ...defaultTheme.fontFamily.sans],
        },
        screens: {
            tablet: '768px',
            laptop: '1024px',
            desktop: '1440px',
            largeDesktop: '1920px',
        },
        fontSize: {
            '2.5': '10px',
            '3': '12px',
            '3.5': '14px',
            '4': '16px',
            '4.5': '18px',
            '5': '20px',
            '5.5': '22px',
            '6': '24px',
            '7': '28px',
            '8': '32px',
            '9': '36px',
            '10': '40px',
            '11': '44px',
            '12': '48px',
            '14': '56px',
            '16': '64px',
            '18': '72px',
            '22': '88px',
            '24': '96px',
            '26': '104px',
        },
    },
    plugins: [require('tailwindcss-animate')],
};
