name: Build Web App and Storybook
on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
      ref:
        description: 'The branch or tag ref to checkout. Default is the branch that triggered the workflow.'
        default: ''
        required: false
        type: string
    secrets:
      NPM_AUTH_TOKEN:
        required: true
      ANKER_API_KEY:
        required: true
      WALLET_CONNECT_ID:
        required: true
      CODECOV_TOKEN:
        required: true
      SQUID_WIDGET_INTEGRATOR_ID:
        required: true

jobs:
  build-and-test-all:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Use Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: |
          cat <<EOF > .env.local
          NEXT_PUBLIC_ANKER_API_KEY=${{ secrets.ANKER_API_KEY }}
          NEXT_PUBLIC_WALLET_CONNECT_ID=${{ secrets.WALLET_CONNECT_ID }}
          NEXT_PUBLIC_SQUID_WIDGET_INTEGRATOR_ID=${{ secrets.SQUID_WIDGET_INTEGRATOR_ID }}
          NEXT_PUBLIC_SET_PRICE_ENABLED=${{ vars.SET_PRICE_ENABLED }}
          SF_ENV=${{ vars.SF_ENV }}
          EOF

      - name: Check Syntax with Prettier
        run: npm run prettier:check

      - name: Check Style with ESLint
        run: npm run lint:check

      - name: Run Tests
        run: npm run test:cov

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit-tests
          files: './coverage/coverage-final.json'

      - name: Build Web App
        run: npm run build

      - name: Publish Web App
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: build
          retention-days: 10
          if-no-files-found: error
