name: Deploy on Fleek

on:
  push:
    branches:
      - develop

jobs:
  identify-env:
    name: Identify the environment
    uses: ./.github/workflows/identify-env.yml
    with:
      branch_name: ${{ github.ref }}

  build-and-test-all:
    name: Build and Test
    needs: identify-env
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: WebApp
      environment_name: ${{ needs.identify-env.outputs.environment_name }}
    secrets: inherit

  deploy-on-fleek:
    runs-on: ubuntu-latest
    name: Deploy on Fleek
    environment: ${{ needs.identify-env.outputs.environment_name }}
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    needs: [identify-env, build-and-test-all]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: WebApp
          path: .deploy/${{ vars.FLEEK_ENV }}/build

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'
            cache: 'npm'

      - name: Install Fleek CLI
        run: npm i -g @fleek-platform/cli

      - name: Deploy Site
        id: deploy
        run: fleek sites deploy --config fleek.${{ vars.FLEEK_ENV }}.json

      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs }}"
